app = "enigme-bot"
primary_region = "cdg" # Paris (Charles de Gaulle)

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8080"
  NODE_OPTIONS = "--max-old-space-size=120"

[mounts]
  source = "enigme_data"
  destination = "/app/data"

[processes]
  app = "node --max-old-space-size=120 src/index.js"

[deploy]
  release_command = "npm run deploy"
